### ISSUE TITLE
Fails to build in 15.7

### ISSUE THREAD

**Issue by rvernica** [Paradigm4/limit#1]
I am having trouble building this against `15.7`. This is the error I get:
```
$ make SCIDB=/usr/src/scidb-15.7.0.9267
make -C src
make[1]: Entering directory '/usr/src/scidb-15.7.0.9267/examples/limit/src'
"/usr/bin/g++-4.9" -W -Wextra -Wall -Wno-unused-parameter -Wno-variadic-macros -Wno-strict-aliasing -Wno-long-long -Wno-unused -fPIC -D_STDC_FORMAT_MACROS -Wno-system-headers -isystem -O3 -g -DNDEBUG -D_STDC_LIMIT_MACROS -std=c++11 -DCPP11 -I. -DPROJECT_ROOT="\"/usr/src/scidb-15.7.0.9267\"" -I"/opt/scidb/15.7/3rdparty/boost/include/" -I"/usr/src/scidb-15.7.0.9267/include" -o liblimit.so plugin.cpp  LogicalLimit.cpp PhysicalLimit.cpp -shared -Wl,-soname,liblimit.so -L. -L"/opt/scidb/15.7/3rdparty/boost/lib" -L"/usr/src/scidb-15.7.0.9267/lib" -Wl,-rpath,/usr/src/scidb-15.7.0.9267/lib: -lm
LogicalLimit.cpp: In member function 'virtual scidb::ArrayDesc scidb::LogicalLimit::inferSchema(std::vector<scidb::ArrayDesc>, std::shared_ptr<scidb::Query>)':
LogicalLimit.cpp:60:28: error: '__gnu_cxx::__alloc_traits<std::allocator<scidb::ArrayDesc> >::value_type' has no member named 'getDistribution'
                 schemas[0].getDistribution(),
                            ^
LogicalLimit.cpp:61:24: error: 'class scidb::Query' has no member named 'getDefaultArrayResidency'
                 query->getDefaultArrayResidency());
                        ^
Makefile:47: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/usr/src/scidb-15.7.0.9267/examples/limit/src'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by rvernica** [comment]
I just noticed the [v15.7 branch](https://github.com/Paradigm4/limit/tree/v15.7). The branch builds fine.
